# Generated by Django 3.2.23 on 2024-03-19 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iogt_users', '0005_auto_20220120_0813'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cranky_uuid',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
